### ISSUE TITLE
Grape Suit (Varia)

### ISSUE THREAD

**Issue by Blooshysaur** [Miepee/AM2R-Custom-Palettes#12]
Creator: Blooshy
Includes the palette and the preview

![Palette](https://user-images.githubusercontent.com/75738280/136661451-f37d0fbb-f043-4403-a041-b5ef9cb1074b.png)
![Preview](https://user-images.githubusercontent.com/75738280/136661483-eca8aeff-21d9-4350-a7eb-9ed6a4f642a0.png)

**Comment by Miepee** [comment]
Added with 27ee130
