### ISSUE TITLE
Dread Inspired Fusion Suits

### ISSUE THREAD

**Issue by TeddyRiggs** [Miepee/AM2R-Custom-Palettes#16]
![Screenshot 2021-11-26 at 08-24-22 maxresdefault jpg (JPEG Image, 1280 × 720 pixels) — Scaled (85%)](https://user-images.githubusercontent.com/94842265/143510423-8f49574e-e8ac-434e-a6e2-d30b4752ca6b.png)

![index](https://user-images.githubusercontent.com/94842265/143510193-2ac61258-4d30-42a0-8a64-c2a10134666a.png)
![index3](https://user-images.githubusercontent.com/94842265/143510237-1e8e8b51-5776-48a7-a668-38c9c5788fb2.png)
![index2](https://user-images.githubusercontent.com/94842265/143510242-b5dc8a3c-f885-43c0-8e82-9fa9a30766b0.png)

Power Suit
![fusion_power](https://user-images.githubusercontent.com/94842265/143510269-d8d45508-e725-4a5d-bdaf-789509ee1031.png)
Varia Suit
![fusion_varia](https://user-images.githubusercontent.com/94842265/143510263-d29bfe17-e039-4149-9b3d-0cae116b5106.png)
Gravity Suit
![fusion_gravity](https://user-images.githubusercontent.com/94842265/143510266-980d096e-484c-4b60-a901-65e0f56172f4.png)

**Comment by WaveKalte** [comment]
how i install this? i know it's like.... 4 years later but damn bruh you cooked. i see nothing but flames cuz this sht fires 🔥

**Comment by Miepee** [comment]
There are instructions in the readme:

https://github.com/Miepee/AM2R-Custom-Palettes?tab=readme-ov-file#using-the-palettes-from-here-for-am2r

If you need more help, you can probably ask in the [AM2R Discord](https://discord.gg/YTQnkAJ 
) server (IIRC tehre should be a channel called #am2r-mods there.)
