### ISSUE TITLE
Another Dread Custom Palette

### ISSUE THREAD

**Issue by TeddyRiggs** [Miepee/AM2R-Custom-Palettes#17]
![indgihex](https://user-images.githubusercontent.com/94842265/143520870-d1d4038f-fc15-4cb7-84d3-f1ae61dce28e.png)
![indebijx](https://user-images.githubusercontent.com/94842265/143520881-388cd884-a6f4-484d-8f4c-e074313a2bdd.png)
![vjgfigiug](https://user-images.githubusercontent.com/94842265/143521034-226fa583-4133-40d1-9c15-8c7905e77ad9.png)

Power Suit
![power](https://user-images.githubusercontent.com/94842265/143521090-87307a86-d896-48eb-9840-3511789ceaec.png)
Varia Suit
![varia](https://user-images.githubusercontent.com/94842265/143521106-baab1e38-942d-424e-b62f-75757ae5cca9.png)
Gravity Suit
![gravity](https://user-images.githubusercontent.com/94842265/143521128-3f6301ca-1fe6-4f46-b137-d103e1ee63e1.png)

**Comment by Eevee-the-Hedgehog** [comment]
Can you do the Spider Ball, Space Jump, and morph ball trails?
