### ISSUE TITLE
Metroid Suit

### ISSUE THREAD

**Issue by TeddyRiggs** [Miepee/AM2R-Custom-Palettes#19]
Metroid suit Pallete for the Gravity Suit
![Metroid_Suit](https://user-images.githubusercontent.com/94842265/143562172-4ca6072b-9d0b-4fb6-bc9e-48105cde74b8.jpg)
![Metroid Suit](https://user-images.githubusercontent.com/94842265/143562187-ecb3a85c-3731-4d89-860f-0f0297e77a7b.png)

Gravity Suit
![gravity](https://user-images.githubusercontent.com/94842265/143562037-73596f26-bba3-4090-ba96-2d9d418ec508.png)

**Comment by Cephalobyte** [comment]
Insane!!

**Comment by Miepee** [comment]
Fixed by above commit
