### ISSUE TITLE
NES Samus

### ISSUE THREAD

**Issue by TeddyRiggs** [Miepee/AM2R-Custom-Palettes#20]
Made some NES inspired Palletes for Samus
![inkn,dex](https://user-images.githubusercontent.com/94842265/143568263-be3f4db5-dd24-48eb-90ce-87d2cd60d341.png)
![inkjkldex](https://user-images.githubusercontent.com/94842265/143568301-3057f2e4-c5bd-48f2-bca4-e5e66366c9de.png)
Gravity suit Purple or Green Version
![indvjvjhbkex](https://user-images.githubusercontent.com/94842265/143568317-48e20baa-cf81-4769-8f4e-e981e75969ad.png)  ![gugjindex](https://user-images.githubusercontent.com/94842265/143570006-82bb1f37-51fb-4be9-8f21-b6f13da96da4.png)

Power suit
![power](https://user-images.githubusercontent.com/94842265/143568350-6544d0d3-c71a-4db3-ba6b-44447fbb23ad.png)
Varia Suit
![varia](https://user-images.githubusercontent.com/94842265/143568420-beae2be4-cd5e-4ad9-a623-7bcaf5ef64d2.png)
Gravity Suit Purple ver.
![gravity](https://user-images.githubusercontent.com/94842265/143568460-89f7ff6b-2a88-40ca-944d-845372c9c0e4.png)
Gravity Suit Green ver.
![gravity](https://user-images.githubusercontent.com/94842265/143570217-8786487e-d931-4e26-85e9-58c632ca12bd.png)

**Comment by Miepee** [comment]
Gonna close this, personally think that they're too bright and saturated and are uncomfortable to look at.
