### ISSUE TITLE
Classic Power Suit Samus

### ISSUE THREAD

**Issue by CorvusHellkite** [Miepee/AM2R-Custom-Palettes#21]
Made Suits Inspired by Samus's Power Suit from NES Metroid
![Metroid-1-Samus](https://user-images.githubusercontent.com/95138464/143688048-8d3163a9-ca40-405f-9a2a-9cf96cbe1ff8.png)

Power
![download](https://user-images.githubusercontent.com/95138464/143687926-c48b6f11-c6e2-47f2-956c-0e8b8b4ed2b5.png)
Varia
![download 1](https://user-images.githubusercontent.com/95138464/143687947-e518a0b8-cbe6-4d3d-9427-cf43d5cebaeb.png)
Gravity
![download (1)](https://user-images.githubusercontent.com/95138464/143687953-9f45b3ed-d64a-4bcd-b43f-e799248618b7.png)
 Power
![power (Classic-themed Power Suit)](https://user-images.githubusercontent.com/95138464/143688083-829276be-7720-4c48-abfc-4bcf4b0b1d4a.png)
Varia
![varia (Classic-themed Power Suit)](https://user-images.githubusercontent.com/95138464/143688095-4f758d09-686f-4bba-8010-4cf4e9285410.png)
Gravity
![gravity (Classic-themed Power Suit)](https://user-images.githubusercontent.com/95138464/143688104-92edadfa-a587-43a5-bf43-b6c5698025a6.png)

**Comment by Miepee** [comment]
Hello, I currently removed the palette from the repository, as I'm planning to relicense this repo under BSD-0 instead of the current All Rights Reserved.
If you're all right with that, please let me know and I'll reimport the palette back.

**Comment by CorvusHellkite** [comment]
That's ok with me thank you I know it's a simple palette but I really like this one
