### ISSUE TITLE
Galactic Federation 07th Platoon Varia Suit

### ISSUE THREAD

**Issue by AbyssalCreature** [Miepee/AM2R-Custom-Palettes#24]
**Creator of the Custom Palette:** Myself.
**Spiderball Glow used belongs to:** _varia (Echoes Dark Suit),_ **_credits to their respective creators._**

**Link or upload the palettes, and if available Morph trails/glow as well**
![varia (GF 07 Platoon)](https://user-images.githubusercontent.com/97541641/148989527-217ee163-81f3-4685-bc1f-ffec8013246e.png) <- Suit *(Rename to "varia.png")*
![varia (GF 07 Platoon)](https://user-images.githubusercontent.com/97541641/148989480-907c4ebb-1f07-4910-83af-0e50de36f53d.png) <- Morphball Trail *(Rename to "varia.png")*
![varia (GF 07 Platoon)](https://user-images.githubusercontent.com/97541641/148989566-d7cd628b-adca-422e-9905-81afa28f9a7f.png) <- Spiderball Glow *(Rename to "varia.png")*

**Captures in game.**
Front View.
![GF 07 Splatoon 1](https://user-images.githubusercontent.com/97541641/148989313-b5d7bd30-c01f-4615-9a99-f9d65cc23e33.png)
Morphball.
![GF 07 Splatoon 2](https://user-images.githubusercontent.com/97541641/148989317-0e23a263-7ea9-48b5-8f0c-003152196e09.png)
Spiderball.
![GF 07 Splatoon 3](https://user-images.githubusercontent.com/97541641/148989319-afcc4c77-31cc-4ce0-bbf0-b1188333b4d4.png)
Side View + Missile Cannon.
![GF 07 Splatoon 4](https://user-images.githubusercontent.com/97541641/148989320-cb9fd35a-07a6-44b7-a030-536d7c9cfec9.png)
Side View.
![GF 07 Splatoon 5](https://user-images.githubusercontent.com/97541641/148989322-46bcdcf2-ced3-4a3c-8e96-f726f896f340.png)
Morphball + Morphtrail.
![GF 07 Splatoon 6](https://user-images.githubusercontent.com/97541641/148989323-bc56d1dc-d9f8-4d9c-a89d-704a679ff3fc.png)
Shinespark mid-air.
![GF 07 Splatoon 7](https://user-images.githubusercontent.com/97541641/148989324-fd5d8d1d-14dd-42e6-93cc-adb367408e96.png)
Space Jump (without Screw Attack).
![GF 07 Splatoon 8](https://user-images.githubusercontent.com/97541641/148989325-30d27f4c-27ef-4bc8-85ea-3e3786613e27.png)

**Comment by Miepee** [comment]
Thanks for submitting the palette!
Unfortunately, I find the end result too noisy and unreadable. Try working on it more, and then opening another issue.
