### ISSUE TITLE
Comic Shadow Samus

### ISSUE THREAD

**Issue by TeddyRiggs** [Miepee/AM2R-Custom-Palettes#25]
Tried to make a Pallete that's more reminiscent to the comic art of Zero Mission by adding darker shadows instead of pixel shading
![Zero-Mission-Wallpaper-Clean-image-courtesy-of-Tumbex](https://user-images.githubusercontent.com/94842265/159105346-169a479d-d3ad-4f95-b557-62437f89fafd.jpg)
![imagedoc-ligjln htnoise](https://user-images.githubusercontent.com/94842265/159105311-e4444300-fdc6-4aba-98c5-464bd5decc0c.png)
![imagedoc-lightnoise](https://user-images.githubusercontent.com/94842265/159105312-96d2fabf-aa22-4896-97ca-3975aee6ced8.png)
![imagedoc-lib,n,ghtnoise](https://user-images.githubusercontent.com/94842265/159105314-ecc9af7e-514e-456c-8451-abc098c948ed.png)

Gravity Suit
![gravity](https://user-images.githubusercontent.com/94842265/159105461-1d143f09-1b01-4abb-9581-cd2b27281271.png)
Power Suit
![power](https://user-images.githubusercontent.com/94842265/159105462-8deeba23-dedf-4db0-954e-9bc1165e13a8.png)
Varia Suit
![varia](https://user-images.githubusercontent.com/94842265/159105463-daf12b8e-afe3-4d80-a050-13bc266249bf.png)

**Comment by Cephalobyte** [comment]
Oooh, that's cool!

**Comment by Miepee** [comment]
Fixed by above commit
