### ISSUE TITLE
GreenSuits1(noFusion)

### ISSUE THREAD

**Issue by Jesright73** [Miepee/AM2R-Custom-Palettes#3]
**By Jesright73**

![GreenSuits](https://user-images.githubusercontent.com/79653967/118881027-96502b00-b8c0-11eb-9068-464b42214e65.png)
Morphball trails, Spacejump, and SpiderGlow included.
[GreenSuits.zip](https://github.com/Miepee/AM2R-Custom-Palettes/files/6511459/GreenSuits.zip) (edited; removed default fusion palettes)

**Comment by Miepee** [comment]
Added thanks!
