### ISSUE TITLE
Bluelight Special (Gravity Only)

### ISSUE THREAD

**Issue by Jesright73** [Miepee/AM2R-Custom-Palettes#4]
**By Jesright73**
Two space jump trails included: an electric blue trail, and a pure white trail.
![BluelightSample](https://user-images.githubusercontent.com/79653967/118883548-5d658580-b8c3-11eb-9e35-f8cf49c17e94.png)
[BluelightSpecial(GravityOnly).zip](https://github.com/Miepee/AM2R-Custom-Palettes/files/6511530/BluelightSpecial.GravityOnly.zip)

**Comment by Miepee** [comment]
Also added, thanks.
